[project]
name = "atalaya-interpreter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.14.2",
]

[project.scripts]
atalaya-interpreter = "atalaya_interpreter:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
