version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/watchman
    schedule:
      interval: weekly
    groups:
      go-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: uv
    directory: /apps/interpreter
    schedule:
      interval: weekly
    groups:
      python-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /apps/command-center
    schedule:
      interval: weekly
    groups:
      frontend-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /apps/watchman
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/interpreter
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/command-center
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
